- src/main/scala/no/ndla/articleapi/controller/ArticleController.scala
- src/main/scala/no/ndla/articleapi/model/ContentApiModels.scala
- src/main/scala/no/ndla/articleapi/service/search/ElasticContentSearchComponent.scala
- src/test/scala/no/ndla/articleapi/service/search/ElasticContentSearchTest.scala
> #3: Added SearchResult as part of response

- .travis.yml
> Slack notify

- build.sbt
- src/main/scala/no/ndla/articleapi/ArticleApiProperties.scala
Avhengig av ack og release av network
> #174: Tatt ibruk fellesfunksjonalitet for Domain

- build.sbt
- src/main/scala/no/ndla/articleapi/controller/ArticleController.scala
- src/main/scala/no/ndla/articleapi/integration/MigrationApiClient.scala
- src/main/scala/no/ndla/articleapi/model/search/SearchableArticle.scala
Update av network lib, var det som skulle til for å få https på alle api urler.
> #86 update network dep - https on api

- src/main/scala/no/ndla/articleapi/ComponentRegistry.scala
- src/main/scala/no/ndla/articleapi/service/ConverterModules.scala
- src/main/scala/no/ndla/articleapi/service/converters/LeafNodeConverter.scala
- src/test/scala/no/ndla/articleapi/TestEnvironment.scala
- src/test/scala/no/ndla/articleapi/service/ConverterServiceTest.scala
- src/test/scala/no/ndla/articleapi/service/converters/LeafNodeConverterTest.scala
Det viser seg at noder som har node type video/h5p_content også kan ha content. Denne PRen inkluderer også eventuelt innhold
> #625: include content in leaf node articles

- src/main/scala/no/ndla/articleapi/ArticleApiProperties.scala
Litt teit å lage PR. på endring av ett tegn, men whatever:p
> use correct version of audio-api

- src/main/resources/mathml-rules.json
Addet manglende tags til rules.
https://developer.mozilla.org/en-US/docs/Web/MathML/Element
> NDLANO/Issues#721 Adds tags to mathml-rules.json

- build.sbt
Oppdaterer for å tillate rowspan og colspan i tables
> #787: Updates validation to 0.8

- build.sbt
- src/main/scala/no/ndla/articleapi/service/converters/HtmlTagGenerator.scala
- src/main/scala/no/ndla/articleapi/service/converters/contentbrowser/LenkeConverterModule.scala
Venter på [denne](https://github.com/NDLANO/validation/pull/9).
> #791 Adds embed support for tv2skole, vg.no and scribd

- src/main/scala/db/migration/V9__TranslateUntranslatedAuthors.scala
- src/main/scala/no/ndla/articleapi/service/ConverterService.scala
- src/test/scala/db/migration/V9__TranslateUntranslatedAuthorsTest.scala
- src/test/scala/no/ndla/articleapi/service/ConverterServiceTest.scala
Also adds better test for import translation of contributors
> #806: Adds migrationscript which fixes untranslated contributors

- src/main/scala/no/ndla/articleapi/controller/ArticleControllerV2.scala
- src/main/scala/no/ndla/articleapi/model/search/SearchableArticle.scala
- src/main/scala/no/ndla/articleapi/service/ConverterService.scala
- src/main/scala/no/ndla/articleapi/service/search/ArticleIndexService.scala
- src/main/scala/no/ndla/articleapi/service/search/ArticleSearchService.scala
- src/main/scala/no/ndla/articleapi/service/search/ConceptIndexService.scala
- src/main/scala/no/ndla/articleapi/service/search/ConceptSearchService.scala
- src/main/scala/no/ndla/articleapi/service/search/SearchConverterService.scala
- src/main/scala/no/ndla/articleapi/service/search/SearchService.scala
- src/test/scala/no/ndla/articleapi/controller/ArticleControllerV2Test.scala
- src/test/scala/no/ndla/articleapi/service/ConverterServiceTest.scala
- src/test/scala/no/ndla/articleapi/service/search/ArticleSearchServiceTest.scala
- src/test/scala/no/ndla/articleapi/service/search/ConceptSearchServiceTest.scala
Reverts NDLANO/article-api#193 because unforeseen Elasticsearch incompatibilities
> Revert "#741 Implements multilanguage search"

- build.sbt
- src/main/scala/db/migration/V12__MoveRelatedContentEmbedsToDivs.scala
- src/main/scala/no/ndla/articleapi/JettyLauncher.scala
- src/test/scala/db/migration/V12__MoveRelatedContentEmbedsToDivsTest.scala
resolves https://github.com/NDLANO/Issues/issues/1042
depends on https://github.com/NDLANO/validation/pull/17
Waiting for validation: https://github.com/NDLANO/validation/pull/17
> #1042: Adds migration script for moving related-content embeds into divs

- build.sbt
resolves https://github.com/NDLANO/Issues/issues/1055
> #1055: Bump validation to 0.18

- build.sbt
connects https://github.com/NDLANO/Issues/issues/1096
> #1096: Bump validation

- build.sbt
Waiting for: https://github.com/NDLANO/validation/pull/22 and https://github.com/NDLANO/validation/pull/21
> #1096, #1104: Bump validation to 0.21

- build.sbt
- src/main/scala/no/ndla/articleapi/ArticleApiProperties.scala
- src/main/scala/no/ndla/articleapi/model/search/SearchableArticle.scala
- src/main/scala/no/ndla/articleapi/model/search/SearchableLanguageFormats.scala
- src/main/scala/no/ndla/articleapi/model/search/SearchableLanguageValues.scala
- src/main/scala/no/ndla/articleapi/service/ConverterService.scala
- src/main/scala/no/ndla/articleapi/service/ReadService.scala
- src/main/scala/no/ndla/articleapi/service/search/ArticleIndexService.scala
- src/main/scala/no/ndla/articleapi/service/search/ConceptSearchService.scala
- src/main/scala/no/ndla/articleapi/service/search/SearchConverterService.scala
- src/test/scala/no/ndla/articleapi/model/search/SearchableArticleSerializerTest.scala
- src/test/scala/no/ndla/articleapi/service/ConverterServiceTest.scala
- src/test/scala/no/ndla/articleapi/service/ReadServiceTest.scala
- src/test/scala/no/ndla/articleapi/service/search/ArticleSearchConverterServiceTest.scala
- src/test/scala/no/ndla/articleapi/service/search/ConceptSearchServiceTest.scala
connects to https://github.com/NDLANO/issues/issues/1058
> #1058: Dynamically adds data-url to file embeds, also converts single embeds to anchors

- build.sbt
- project/assembly.sbt
- project/build.properties
- project/plugins.sbt
- src/main/scala/no/ndla/articleapi/controller/InternController.scala
- src/main/scala/no/ndla/articleapi/controller/NdlaController.scala
- src/main/scala/no/ndla/articleapi/model/api/NDLAErrors.scala
- src/main/scala/no/ndla/articleapi/repository/ArticleRepository.scala
- src/main/scala/no/ndla/articleapi/service/WriteService.scala
- src/test/scala/no/ndla/articleapi/controller/InternControllerTest.scala
- src/test/scala/no/ndla/articleapi/repository/ArticleRepositoryTest.scala
- src/test/scala/no/ndla/articleapi/service/WriteServiceTest.scala
> update external ids on publish #1152

- src/main/scala/no/ndla/articleapi/controller/ArticleControllerV2.scala
- src/main/scala/no/ndla/articleapi/controller/InternController.scala
- src/main/scala/no/ndla/articleapi/model/api/ArticleIds.scala
- src/main/scala/no/ndla/articleapi/service/ConverterService.scala
- src/main/scala/no/ndla/articleapi/service/ReadService.scala
resolves https://github.com/NDLANO/Issues/issues/1164
> #1164: Moves external_ids endpoint to ArticleControllerV2

- src/main/scala/db/migration/V14__MoveToNewFileEmbedFormat.scala
- src/test/scala/db/migration/V14__MoveToNewFileEmbedFormatTest.scala
resolves https://github.com/NDLANO/Issues/issues/1168
> #1168: Adds migration for not storing file-url in database

- src/main/scala/no/ndla/articleapi/repository/ArticleRepository.scala
- src/test/scala/no/ndla/articleapi/repository/ArticleRepositoryTest.scala
connects to https://github.com/NDLANO/Issues/issues/1170
> #1170: Fetching externalIds of articles without external ids no longer fails

- src/main/scala/no/ndla/articleapi/integration/Elastic4sClient.scala
connects to https://github.com/NDLANO/Issues/issues/1177
> #1177: Sets longer timeout for elastic4s client

- build.sbt
- src/main/scala/no/ndla/articleapi/ArticleApiProperties.scala
- src/main/scala/no/ndla/articleapi/JettyLauncher.scala
> Added javamelody to component

- build.sbt
- src/main/scala/db/migration/V16__UpdateLicenses.scala
- src/main/scala/no/ndla/articleapi/service/ConverterService.scala
- src/main/scala/no/ndla/articleapi/service/search/ArticleSearchService.scala
- src/test/scala/db/migration/V16__UpdateLicesnsesTest.scala
- src/test/scala/no/ndla/articleapi/TestData.scala
- src/test/scala/no/ndla/articleapi/service/ConverterServiceTest.scala
- src/test/scala/no/ndla/articleapi/service/search/ArticleSearchServiceTest.scala
- src/test/scala/no/ndla/articleapi/validation/ContentValidatorTest.scala
connected to NDLANO/Issues#1100
> update cc licenses #1100

- build.sbt
connects to NDLANO/Issues#1300
> #1300: Bump validation

- src/main/scala/no/ndla/articleapi/repository/ArticleRepository.scala
- src/test/scala/no/ndla/articleapi/repository/ArticleRepositoryTest.scala
> Ignore missing article when delete. Mission accomplished

- src/main/scala/no/ndla/articleapi/model/api/ArticleTitle.scala
- src/main/scala/no/ndla/articleapi/model/domain/ArticleContent.scala
- src/main/scala/no/ndla/articleapi/model/domain/ArticleIntroduction.scala
- src/main/scala/no/ndla/articleapi/model/domain/ArticleMetaDescription.scala
- src/main/scala/no/ndla/articleapi/model/domain/ArticleMetaImage.scala
- src/main/scala/no/ndla/articleapi/model/domain/ArticleTag.scala
- src/main/scala/no/ndla/articleapi/model/domain/ArticleTitle.scala
- src/main/scala/no/ndla/articleapi/model/domain/ConceptContent.scala
- src/main/scala/no/ndla/articleapi/model/domain/ConceptTitle.scala
- src/main/scala/no/ndla/articleapi/model/domain/Language.scala
- src/main/scala/no/ndla/articleapi/model/domain/LanguageField.scala
- src/main/scala/no/ndla/articleapi/model/domain/VisualElement.scala
- src/main/scala/no/ndla/articleapi/model/search/SearchableLanguageValues.scala
- src/main/scala/no/ndla/articleapi/service/ConverterService.scala
- src/main/scala/no/ndla/articleapi/validation/ContentValidator.scala
- src/test/scala/no/ndla/articleapi/validation/ContentValidatorTest.scala
> #1408:Better validation message when no tags are defined

- build.sbt
- src/main/scala/no/ndla/articleapi/ArticleApiProperties.scala
connected to NDLANO/Issues#1439
Avhenger av at https://github.com/NDLANO/network/pull/38 merges før denne bygger
> update network library version #1439

- build.sbt
- pact.sbt
- project/plugins.sbt
- src/main/scala/no/ndla/articleapi/controller/InternController.scala
- src/main/scala/no/ndla/articleapi/repository/ArticleRepository.scala
- src/main/scala/no/ndla/articleapi/service/WriteService.scala
- src/test/scala/no/ndla/articleapi/TestData.scala
- src/test/scala/no/ndla/articleapi/consumerdrivencontracts/ArticleApiProviderCDCTest.scala
- src/test/scala/no/ndla/articleapi/repository/ArticleRepositoryTest.scala
- src/test/scala/no/ndla/articleapi/service/WriteServiceTest.scala
connects to NDLANO/Issues#1485
> #1485: Removes allocateArticle endpoint and functions and adds articleRepository tests

- src/test/scala/no/ndla/articleapi/consumerdrivencontracts/ArticleApiProviderCDCTest.scala
Noen ganger litt tregt på travis. Som gjør at testene ikke passer hver gang :)
> Makes provider interaction requests have longer timeout

- build.sbt
connects to NDLANO/Issues#1508
> #1508: Bumps validation to 0.30

- src/test/scala/no/ndla/articleapi/integration/DraftApiClientTest.scala
connects to NDLANO/Issues#1476
> #1476: Adds token to article-api pact test

- src/main/scala/db/migration/R__SetArticleTypeFromTaxonomy.scala
- src/test/scala/db/migration/R__SetArticleTypeFromTaxonomyTest.scala
connects to NDLANO/Issues#1530
> #1530: Adds repeatable migration based on taxonomy

- src/main/scala/no/ndla/articleapi/controller/InternController.scala
- src/main/scala/no/ndla/articleapi/service/search/IndexService.scala
- src/test/scala/no/ndla/articleapi/controller/InternControllerTest.scala
Connects to NDLANO/Issues#1532
> #1532: Add delete index method

- build.sbt
- src/main/scala/db/migration/R__SetLanguageFromTaxonomy.scala
Connects to NDLANO/Issues#1607
> NDLANO/Issues#1607: keywords and language migration script

- build.sbt
Connects to NDLANO/Issues#1817
> Bump validation lib

- .travis.yml
- build.sbt
- project/build.properties
- project/plugins.sbt
- src/test/scala/no/ndla/articleapi/UnitSuite.scala
- src/test/scala/no/ndla/articleapi/consumerdrivencontracts/ArticleApiProviderCDCTest.scala
Depends on: NDLANO/search-api/pull/80
> #1887: Adds search-api as pact consumer

- src/main/scala/db/migration/V23__RenameCompetences.scala
- src/main/scala/no/ndla/articleapi/controller/ArticleControllerV2.scala
- src/main/scala/no/ndla/articleapi/model/api/ArticleSearchParams.scala
- src/main/scala/no/ndla/articleapi/model/api/ArticleSummary.scala
- src/main/scala/no/ndla/articleapi/model/domain/Content.scala
- src/main/scala/no/ndla/articleapi/model/domain/SearchSettings.scala
- src/main/scala/no/ndla/articleapi/model/search/SearchableArticle.scala
- src/main/scala/no/ndla/articleapi/service/ConverterService.scala
- src/main/scala/no/ndla/articleapi/service/search/ArticleIndexService.scala
- src/main/scala/no/ndla/articleapi/service/search/ArticleSearchService.scala
- src/main/scala/no/ndla/articleapi/service/search/SearchConverterService.scala
- src/test/scala/db/migration/V23__RenameCompetencesTest.scala
- src/test/scala/no/ndla/articleapi/consumerdrivencontracts/ArticleApiProviderCDCTest.scala
- src/test/scala/no/ndla/articleapi/controller/ArticleControllerV2Test.scala
- src/test/scala/no/ndla/articleapi/model/search/SearchableArticleSerializerTest.scala
- src/test/scala/no/ndla/articleapi/service/search/ArticleSearchServiceTest.scala
https://github.com/NDLANO/Issues/issues/2039
> renamed competences to grepCodes

- src/main/scala/no/ndla/articleapi/model/api/Article.scala
- src/main/scala/no/ndla/articleapi/service/ConverterService.scala
- src/test/scala/no/ndla/articleapi/TestData.scala
https://github.com/NDLANO/Issues/issues/2056
> added grepCodes to api.Article

- build.sbt
[Issue #2037](https://github.com/NDLANO/Issues/issues/2037)
> Validation version with new math tags

- build.sbt
https://github.com/NDLANO/Issues/issues/2233
https://github.com/NDLANO/Issues/issues/1998
> bump validation with updated ol tag and added code-block embed tag

- build.sbt
- src/main/scala/db/migration/V25__AddDataTypeForConcept.scala
- src/test/scala/db/migration/V25__AddDataTypeToConceptTest.scala
> Added data-type inline

- src/main/scala/no/ndla/articleapi/model/api/PartialPublishArticle.scala
- src/main/scala/no/ndla/articleapi/service/ConverterService.scala
- src/main/scala/no/ndla/articleapi/service/WriteService.scala
- src/test/scala/no/ndla/articleapi/service/WriteServiceTest.scala
Partialy fixxes https://github.com/NDLANO/Issues/issues/2402
How to test:
1: Git-Pull branch locally
2: send request to `/article-api/v2/articles/partial-publish/:id?language=":lang"` with body
```
{
"license":"new license",
"tags":["newTag1", "newTag2", "newTag3"],
"metaDescription":"NewMetaDesc"
}
```
3: check that the fields actualy were updated
3a: check that you get an error message if you send invalid data
> extended partial publish method with license, tags and metaDescription

- build.sbt
Tilhører NDLANO/Issues#2410
Oppdaterer validation-versjon. Se: https://github.com/NDLANO/validation/pull/47
> 2410 inline visning av pdf i artikkel

- README.md
- src/main/scala/no/ndla/articleapi/controller/InternController.scala
- src/main/scala/no/ndla/articleapi/model/api/Article.scala
- src/main/scala/no/ndla/articleapi/model/api/PartialPublishArticle.scala
- src/main/scala/no/ndla/articleapi/model/domain/ArticleMetaDescription.scala
- src/main/scala/no/ndla/articleapi/model/domain/Availability.scala
- src/main/scala/no/ndla/articleapi/model/domain/Content.scala
- src/main/scala/no/ndla/articleapi/repository/ArticleRepository.scala
- src/main/scala/no/ndla/articleapi/service/ConverterService.scala
- src/test/scala/no/ndla/articleapi/TestData.scala
- src/test/scala/no/ndla/articleapi/controller/ArticleControllerV2Test.scala
- src/test/scala/no/ndla/articleapi/controller/InternControllerTest.scala
- src/test/scala/no/ndla/articleapi/repository/ArticleRepositoryTest.scala
- src/test/scala/no/ndla/articleapi/service/ConverterServiceTest.scala
> 2414 utvide artikkel med et ekstra felt

- src/main/scala/no/ndla/articleapi/controller/ArticleControllerV2.scala
- src/main/scala/no/ndla/articleapi/controller/InternController.scala
- src/main/scala/no/ndla/articleapi/controller/NdlaController.scala
- src/main/scala/no/ndla/articleapi/model/domain/Content.scala
- src/test/scala/no/ndla/articleapi/repository/ArticleRepositoryTest.scala
Se https://github.com/NDLANO/draft-api/pull/259
> 2448 bugfix parse number as long

- build.sbt
> #2495: Bump validation

- src/main/scala/no/ndla/articleapi/controller/InternController.scala
- src/main/scala/no/ndla/articleapi/model/api/PartialPublishArticle.scala
- src/main/scala/no/ndla/articleapi/service/ConverterService.scala
- src/test/scala/no/ndla/articleapi/service/ConverterServiceTest.scala
Fikser https://github.com/NDLANO/Issues/issues/2482
La til relatedContent til partialPublish flyten
> 2482 automatpublisering av partial publish fields

- build.sbt
Bumper validation for å kunne sette inn statisk.ndla.no som iframe i artikkel.
> Bumped validation to get support for ndla-urls

- src/main/scala/no/ndla/articleapi/repository/ArticleRepository.scala
- src/test/scala/no/ndla/articleapi/repository/ArticleRepositoryTest.scala
Fixing exception thrown because same article has several rows in database.
> Fetching distinct id

- README.md
- src/main/scala/no/ndla/articleapi/ArticleApiProperties.scala
- src/main/scala/no/ndla/articleapi/ArticleSwagger.scala
- src/main/scala/no/ndla/articleapi/model/domain/Language.scala
- src/main/scala/no/ndla/articleapi/service/search/SearchService.scala
- src/main/scala/no/ndla/articleapi/validation/ContentValidator.scala
- src/test/scala/no/ndla/articleapi/TestData.scala
- src/test/scala/no/ndla/articleapi/service/ReadServiceTest.scala
- src/test/scala/no/ndla/articleapi/validation/ContentValidatorTest.scala
Gjør det mulig å konfigurere ndla-spesifikke variabler slik at applikasjonen kan kjøres av andre.
> Added several env variables. Removed unused variables.

- src/main/scala/no/ndla/articleapi/ArticleApiProperties.scala
- src/main/scala/no/ndla/articleapi/validation/ContentValidator.scala
- src/test/scala/no/ndla/articleapi/validation/ContentValidatorTest.scala
Fant korrekt url til h5p scriptet.
> Readd h5p script  with correct url

- src/main/scala/no/ndla/articleapi/model/api/ArticleSummary.scala
- src/main/scala/no/ndla/articleapi/service/ConverterService.scala
- src/test/scala/no/ndla/articleapi/service/ConverterServiceTest.scala
NDLANO/Issues#2751
Returnerer availability
> Returns availabilty for articlesummary

- build.sbt
https://github.com/NDLANO/Issues/issues/2740
> validation bump, adds trinket.io as new supported embed type

- build.sbt
NDDLANO/Issues#2857
Add codepen.io
> Bumped validation

- build.sbt
Oppdaterer til ny validation i forbindelse med NDLANO/Issues#2859. Legger til støtte for flere html-tags.
> Upgrade validation

- build.sbt
Relatert til NDLANO/Issues#2859
Legger til class og headers som lovlige attributter i tabell-celler
> Bump validation
