NDLANO/article-api

src/main/scala/no/ndla/articleapi/controller/InternController.scala, src/main/scala/no/ndla/articleapi/model/domain/HtmlFaultRapport.scala, src/main/scala/no/ndla/articleapi/repository/ArticleRepository.scala, src/main/scala/no/ndla/articleapi/service/ArticleContentInformation.scala, src/test/scala/no/ndla/articleapi/TestData.scala, src/test/scala/no/ndla/articleapi/controller/InternControllerTest.scala
P.t. tar det 20 min (gitt dagens ca 15000 artikler kjørende i IntelliJ) før den terminerer, aka browsern står å jobber i 20 min på en blank skjerm før det kommer en csv fil. Bør være noe frontend spinnere el.l. i forkant hvis noen andre enn "oss" skal bruke det.
=> #277 Route for csv report on html faults

src/main/resources/html-rules.json, src/main/scala/no/ndla/articleapi/service/converters/HtmlTagGenerator.scala, src/main/scala/no/ndla/articleapi/service/converters/contentbrowser/FilConverterModule.scala, src/main/scala/no/ndla/articleapi/service/converters/contentbrowser/LenkeConverterModule.scala, src/test/scala/no/ndla/articleapi/service/converters/contentbrowser/LenkeConverterTest.scala
Bare to av nodene som er referert til i mailen har en lightbox hvor en ekstern kilde åpnes i en lightbox. Hvorav en av dem ikke lar seg importere fga. flash (tror jeg).
Fikset det ene tilfellet. I tilegg til dette defaulter "insertion metode" til en a-tag som åpnes i en ny fane.
=> open in new tab if link was lightbox

src/main/scala/no/ndla/articleapi/model/api/Concept.scala, src/main/scala/no/ndla/articleapi/model/domain/Content.scala, src/main/scala/no/ndla/articleapi/model/domain/Copyright.scala, src/main/scala/no/ndla/articleapi/service/ConverterService.scala, src/test/scala/no/ndla/articleapi/TestData.scala
Fikk vite på forrige spolemøte at de nylig har "skrudd på" lisens for begrep også. Hittil har begreper ikke hatt lisens tilknyttet seg, men nå kan det altså forekomme
=> add optional copyright to concepts #498

src/main/scala/no/ndla/articleapi/service/converters/HTMLCleaner.scala, src/test/scala/no/ndla/articleapi/service/converters/HTMLCleanerTest.scala
Comments i `style`-tags tolkes av Jsoup som [`#data`](https://jsoup.org/apidocs/org/jsoup/nodes/DataNode.html), og dette oppdateres ikke når du unwrapper `style` tags.
=> #682: Comments in styletags should be removed

src/main/scala/no/ndla/articleapi/controller/InternController.scala, src/main/scala/no/ndla/articleapi/service/search/ArticleSearchService.scala, src/main/scala/no/ndla/articleapi/service/search/ConceptSearchService.scala
Gets executioncontext from executorservice in multiple places so that we may spawn as many
threads as we please rather than being limited by the global setting (one per cpucore)
=> #881: Sets executionContext for Futures.

src/main/resources/db/migration/V13__ExternalIdAsArray.sql, src/main/scala/no/ndla/articleapi/controller/InternController.scala, src/main/scala/no/ndla/articleapi/model/domain/package.scala, src/main/scala/no/ndla/articleapi/repository/ArticleRepository.scala, src/main/scala/no/ndla/articleapi/repository/ConceptRepository.scala, src/main/scala/no/ndla/articleapi/service/ConverterService.scala, src/main/scala/no/ndla/articleapi/service/WriteService.scala, src/test/scala/no/ndla/articleapi/repository/ArticleRepositoryTest.scala, src/test/scala/no/ndla/articleapi/service/ConverterServiceTest.scala, src/test/scala/no/ndla/articleapi/service/ReadServiceTest.scala, src/test/scala/no/ndla/articleapi/service/WriteServiceTest.scala
connects to https://github.com/NDLANO/Issues/issues/1146
First id should always be the main node id.
```
GET /intern/external_ids/170178
{
"articleId": 1,
"externalId": [
"170165",
"170178"
]
}
```
=> #1146: Stores all externalIds in database and adds endpoint fetching ids

build.sbt
Tenkte elastic4s hadde oppgradert denne selv, men det hadde de visst ikke ¯\_(ツ)_/¯
=> Adds back specifying jackson version for security reasons

src/main/scala/db/migration/V24__RemoveDomainFromH5PUrl.scala, src/main/scala/no/ndla/articleapi/service/WriteService.scala, src/main/scala/no/ndla/articleapi/validation/ContentValidator.scala, src/test/scala/no/ndla/articleapi/validation/ContentValidatorTest.scala
Publisering av artikler via script feiler dersom metaDescription er tom. Disse artiklene blei importert uten metadescription og blei publisert som en del av importen, så det burde være mogeleg å publisere dei ved å spesifisere import-flagget.
=> Allow empty metadescription

src/main/scala/no/ndla/articleapi/controller/ArticleControllerV2.scala, src/main/scala/no/ndla/articleapi/controller/InternController.scala, src/main/scala/no/ndla/articleapi/model/api/PartialPublishArticle.scala, src/main/scala/no/ndla/articleapi/service/WriteService.scala
Jeg elsker ikke at revision ender opp med å mismatche draft-api når vi gjør sånne ting som det her, men er kanskje vanskelig å unngå.
=> #2180: Adds simple partial publish for grepCodes

src/main/scala/no/ndla/articleapi/controller/InternController.scala
Gjør det enklere i scriptet siden de andre apiene også støtter trailing slash på dumping
=> Make trailing slash optional for article dump endpoint

src/main/resources/db/migration/V26__AddArticleId.sql, src/main/scala/db/migration/R__SetArticleLanguageFromTaxonomy.scala, src/main/scala/no/ndla/articleapi/controller/ArticleControllerV2.scala, src/main/scala/no/ndla/articleapi/controller/InternController.scala, src/main/scala/no/ndla/articleapi/controller/NdlaController.scala, src/main/scala/no/ndla/articleapi/model/api/Article.scala, src/main/scala/no/ndla/articleapi/model/domain/Content.scala, src/main/scala/no/ndla/articleapi/repository/ArticleRepository.scala, src/main/scala/no/ndla/articleapi/service/ConverterService.scala, src/main/scala/no/ndla/articleapi/service/ReadService.scala, src/main/scala/no/ndla/articleapi/service/WriteService.scala, src/test/scala/no/ndla/articleapi/controller/ArticleControllerV2Test.scala, src/test/scala/no/ndla/articleapi/repository/ArticleRepositoryTest.scala, src/test/scala/no/ndla/articleapi/service/WriteServiceTest.scala
Relates to NDLANO/Issues#2329
- Kan hende spesifikk revisjon med `/article-api/v2/articles/1?revision=1`
- Hvis den ikke blir oppgitt så velger den siste
- Dersom siste revision er `unpublished`/`null` i databasen så får man 404 dersom man ikke spør om en spesifikk revision.
- unpublish- og delete-endepunktene velger siste revision by default, men støtter også spesifikk revision med `?revision=1`
=> #2329: Keeps all published versions in database

.travis.yml, src/test/scala/no/ndla/articleapi/consumerdrivencontracts/ArticleApiProviderCDCTest.scala
Skal forhåpentligvis fikse minneproblemene på travis under pact-testene.
Kjører bare test suiter som heter noe med *consumerdrivencontracts* (Som er det pakkenavnet hvor pact-testene ligger).
Da slipper vi å spawne docker-containere (Som bruker masse minne) for alle testsuiter vi hopper over tester i dersom vi bruker tags slik som tidligere.
Grunnen til at det ikke skjer ved vanlig sbt test er fordi vi ikke hopper over testene så containere rekker å bli slettet før vi har for mange samtidig til at minnet blir fullt.
=> Only spawn pact suite when running pact tests

src/main/scala/no/ndla/articleapi/controller/ArticleControllerV2.scala, src/test/scala/no/ndla/articleapi/TestData.scala, src/test/scala/no/ndla/articleapi/controller/ArticleControllerV2Test.scala, src/test/scala/no/ndla/articleapi/service/search/ArticleSearchServiceTest.scala
Fikser så søk med search-context=initial (og de andre) fungerer som forventet og returnerer en search-context header
Søk uten search-context returnerer ingenting
=> Relates to NDLANO/Issues#2434

src/main/scala/no/ndla/articleapi/model/api/Article.scala, src/main/scala/no/ndla/articleapi/model/api/RelatedContentLink.scala, src/main/scala/no/ndla/articleapi/model/api/package.scala, src/main/scala/no/ndla/articleapi/model/domain/Content.scala, src/main/scala/no/ndla/articleapi/model/domain/RelatedContentLink.scala, src/main/scala/no/ndla/articleapi/model/domain/package.scala, src/main/scala/no/ndla/articleapi/service/ConverterService.scala, src/test/scala/no/ndla/articleapi/TestData.scala
Relatert til NDLANO/Issues#2448
Se gjerne på https://github.com/NDLANO/draft-api/pull/253 samtidig.
Legger til et nytt felt i artikkel med relatert innhold. Dette skal på mange måter være likt som relaterte forklaringer som er en liste med id-er. Listen over relatert innhold skal også kunne innholde eksterne lenker (tittel+url).
=> 2448 related content as article metadata

src/main/scala/no/ndla/articleapi/service/ReadService.scala
Se diskusjon NDLANO/Issues#2483.
Sørger for at embeds får riktig base-url (feks h5p-staging.ndla.no i stedet for h5p.ndla.no)
=> getArticleDomainDump add url on embed resource

.gitignore, src/main/scala/no/ndla/articleapi/ComponentRegistry.scala, src/main/scala/no/ndla/articleapi/controller/ArticleControllerV2.scala, src/main/scala/no/ndla/articleapi/integration/FeideApiClient.scala, src/main/scala/no/ndla/articleapi/model/api/NDLAErrors.scala, src/main/scala/no/ndla/articleapi/model/domain/SearchSettings.scala, src/main/scala/no/ndla/articleapi/model/search/SearchableArticle.scala, src/main/scala/no/ndla/articleapi/service/ReadService.scala, src/main/scala/no/ndla/articleapi/service/search/ArticleIndexService.scala, src/main/scala/no/ndla/articleapi/service/search/ArticleSearchService.scala, src/main/scala/no/ndla/articleapi/service/search/SearchConverterService.scala, src/test/scala/no/ndla/articleapi/TestData.scala, src/test/scala/no/ndla/articleapi/TestEnvironment.scala, src/test/scala/no/ndla/articleapi/controller/ArticleControllerV2Test.scala, src/test/scala/no/ndla/articleapi/model/search/SearchableArticleSerializerTest.scala, src/test/scala/no/ndla/articleapi/service/ConverterServiceTest.scala, src/test/scala/no/ndla/articleapi/service/ReadServiceTest.scala, src/test/scala/no/ndla/articleapi/service/search/ArticleSearchServiceTest.scala
Fixes NDLANO/Issues#2609
Kan testes ved å gjøre en request mot apiet etter en artikkel som bare skal vises for lærere feks, og sjekke at den returnerer 404, og ikke dukker opp i søk.
For å teste auth tilgang så må du ha et valid accessToken fra feide og sende det i `FeideAuthorization` headeren.
(Åpen for endring av dette navnet :smile: men å endre til det vanlige `Authorization` krever en jobb i api-gateway, og er kanskje tilogmed litt vanskelig siden vi ikke kan validere uuid'ene på noe vis.)
=> #2609: Filter response based on access with FEIDE credentials

src/main/scala/db/migration/V32__FullbreddeImagesToFull.scala, src/test/scala/db/migration/V32__FullbreddeImagesToFullTest.scala
NDLANO/Issues#2665
Depends on https://github.com/NDLANO/editorial-frontend/pull/1119
Kan testes ved å sjekke at bilder (i content og visualElement) blir migrert fra `fullbredde` til `full` i data-size.
=> #2665: Adds migration to convert `fullbredde` to `full` for images `data-size`

src/main/scala/no/ndla/articleapi/service/ReadService.scala
Dersom du kjem utenfra og går rett på adressa, er det bedre om du får 403 enn 404 for en artikkel du ikkje har lov å sjå.
=> Return 403 if no token.

src/main/scala/no/ndla/articleapi/controller/ArticleControllerV2.scala, src/main/scala/no/ndla/articleapi/model/domain/Cachable.scala, src/main/scala/no/ndla/articleapi/service/ReadService.scala, src/test/scala/no/ndla/articleapi/controller/ArticleControllerV2Test.scala, src/test/scala/no/ndla/articleapi/model/CachableTest.scala, src/test/scala/no/ndla/articleapi/service/ReadServiceTest.scala
Denne infører en hjemmelaget klasse `Cachable` for å ha kontroll på hvorvidt et resultat fra en respons skal caches eller ei.
Kan testes ved å sjekke at artikler med annen `availability` enn `everyone` vil inkludere en `cache-control: private` i responsheaderen. 
Vi burde nok også finne på noe "andre veien" (i api-gateway), sånn at folk med tilganger ikke ender opp med en respons med for lite innhold fra en cache.
For eksempel ved å inkludere feide-tokenet i cache-key'en. Det vil gjøre cachen litt mindre effektiv, men da vil i alle fall innholdet være riktig.
=> Introduce `Cachable` class to avoid caching restricted content

src/main/scala/no/ndla/articleapi/controller/NdlaController.scala, src/main/scala/no/ndla/articleapi/model/api/NDLAErrors.scala, src/main/scala/no/ndla/articleapi/service/ReadService.scala
Dette vil gjøre at et søk med et invalid feidetoken vil oppføre seg som et vanlig søk uten token :^)
Kan testes ved å spinne opp apiet og gjøre et søk med et invalid feidetoken.
=> Ignore errors when fetching userinformation from feide
